version: "3.8"

services:
  asyncapi:
    build: .
    image: jsiddhanth0/asyncapi:latest
    ports:
      - "5000:5000"
    volumes:
    - ./target:/app:ro 
    environment:
      - PORT=5000

      

