version: "3.8"

services:
  my-spring-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
    - ./target:/app:ro 
    environment:
      - PORT=5000
stages {
  # ... other stages ...
  deploy:
    steps:
      - script: sh sudo docker-compose up  # Run your deployment script
  post-health-check:
    when:
      success: deploy  # Run only if deploy stage succeeds
    steps:
      - script: |
          curl http://localhost:8080/actuator/health  # Replace with your URL
          retry: 3
          timeout: 30
          exit $?
}
