version: "3.8"

services:
  my-spring-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
    - ./target:/app:ro 
    environment:
      - PORT=5000
      post:
        always:
          steps:
            - script: curl http://localhost:8080/actuator/health  # Replace with your URL
            retry: 3
            timeout: 30
